spring:
  application:
     name: accounts-service
  datasource:
     driver-class-name: nl.topicus.jdbc.CloudSpannerDriver
     show-sql: true
     hibernate:
        ddl-auto: update
     properties:
        hibernate:
          dialect: nl.topicus.hibernate.dialect.CloudSpannerDialect
security:
  basic:
    enabled: false
